version: '3.9'

networks:
  chatbot_network:

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    container_name: chatbot-postgres
    restart: always
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DATABASE
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - chatbot_network

  bot:
    container_name: ${container_name}
    build:
      context: .
      dockerfile: Dockerfile
    command: python chatbot
    volumes:
      - .:/home/app
    networks:
      - chatbot_network
    restart: always
    env_file:
      - '.env'
    depends_on:
      - postgres
      - redis

  redis:
    container_name: chatbot-redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - chatbot_network
